title: CasFer Tech
description: Blog by CasFer Technologies Pvt. Ltd. (opc)
author: CasFer Tech
logo: /static/img/logo.png
github: https://github.com/casfertech
about: Freelancer, developer, Blogger,  product sourcing

baseurl: ""
url: "http://casfertechnologies.com/"

disqus_shortname: casfertech-github-io
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
